### ISSUE TITLE
Request  support with Accelerometer sensor?

### ISSUE THREAD

**Issue by Johnsonmaung** [SchibstedSpain/parallax-layer-layout#14]
Because " Sadly, there are some low-end phones that doesn't have it. ", as you said. Thanks. Work awesome on others phone.

**Comment by Sloy** [comment]
Hi @Johnsonmaung! 
We tried implementing the feature just with accelerometer and it became too hard. We decided to sacrifice this feature on that kind of devices because the effort to make it work was not worth it.
But we're still open to contributions!
