### ISSUE TITLE
Doesn't work on Samsung

### ISSUE THREAD

**Issue by Kraahkan** [SchibstedSpain/parallax-layer-layout#8]
E/SensorManager: sensor or listener is null on Galaxy Grand Prime (5.1.1).  Works just fine on Nexus 5X (7.0).

**Comment by Sloy** [comment]
Hi @Kraahkan.
We were able to reproduce the issue in a Galaxy J5. We will investigate and fix it. 

Thanks for the report! If you have any idea that can help us fix this faster it's welcomed. 😄

**Comment by Sloy** [comment]
Hi @Kraahkan. We found out that this problem is due to some devices not having the required gyroscope or compass. That's the case in our Galaxy J5, and I guess it's the same thing on your device.

We can't do anything against that. We're updating the Readme on #9 to explain this problem. Thank you!

**Comment by Kraahkan** [comment]
Hey Rafa, thanks for getting back to me!  I didn't even consider that a
modern smartphone wouldn't include a gyroscope.  Glad for the explanation
and the free library of course =D. Cheers
